return {
  "nvim-treesitter/nvim-treesitter",
  build = ':TSUpdate',
  branch = "master",
  lazy = false,
  main = 'nvim-treesitter.configs',
  opts = {
    ensure_installed = {
      "angular",
      "bash",
      "c",
      "c_sharp",
      "cmake",
      "cpp",
      "css",
      "csv",
      "dockerfile",
      "gitignore",
      "go",
      "helm",
      "html",
      "java",
      "javascript",
      "json",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "prisma",
      "rust",
      "scss",
      "sql",
      "svelte",
      "tsx",
      "typescript",
      "xml",
      "yaml"
    },
    auto_install = true,
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'ruby' },
    },
    indent = { enable = true, disable = { 'ruby' } },
  },
}
